###
GET http://localhost:8080/
Accept: application/json

###
GET http://localhost:8080/profile
Accept: application/json



###
GET http://localhost:8080/sakila
Accept: application/json

###
GET http://localhost:8080/sakila/2
Accept: application/json


###
POST http://localhost:8080/sakila
Content-Type: application/json

{
    "name": "Chinese",
    "last":"2021-10-04T23:34:57.000+00:00"
}


###
PUT http://localhost:8080/sakila/3
Content-Type: application/json

{
    "name": "French 1",
    "last": "2021-10-04T23:34:57.000+00:00"
}

###
DELETE http://localhost:8080/sakila/1
